import type { Metadata } from "next";
import { Instrument_Sans } from "next/font/google";
import "./globals.css";
import Providers from "./Providers";
import { AppHeader } from "./widgets/AppHeader";
import { AppFooter } from "./widgets/AppFooter";
// import { SpeedInsights } from "@vercel/speed-insights/next";

const instrumentSans = Instrument_Sans({
  variable: "--font-Instrument-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <script src="https://telegram.org/js/telegram-web-app.js" />
      </head>
      <body className={`${instrumentSans.variable} antialiased`}>
        <Providers>
          <div className="flex flex-col">
            <AppHeader />
            <main className="">
              <div className="">{children}</div>
            </main>
            <AppFooter />
          </div>
        </Providers>
        {/* <SpeedInsights /> */}
      </body>
    </html>
  );
}
